### ISSUE TITLE
Resetting to OFF state every time when app open from background  

### ISSUE THREAD

**Issue by savadmv** [boringdeveloper/FlutterSwitch#11]
Switch the Button to ON state. Open some other application then come back to our application. The switch will be in the OFF state

**Comment by boringdeveloper** [comment]
Hi @savadmv , are you using the latest version of the package. I tried to recreate the reported issue but to no avail.

**Comment by savadmv** [comment]
Yeah. Tried with the latest version. It's working. Thanks
