### ISSUE TITLE
Switching animation only has 3 frames

### ISSUE THREAD

**Issue by jay-lan** [boringdeveloper/FlutterSwitch#17]
I notice the animation is not smooth when I use this widget. then I enable slow animations to observe the animation, I found the animation only has 3 frames.
To solve this problem, I changed part of the code to the following figure.
![image](https://user-images.githubusercontent.com/21981512/102313502-b7c48800-3fab-11eb-8d1c-2d5dbff6cd83.png)

It works well for me now.

**Comment by gutisalex** [comment]
I solved this issue by using a stack: 

```dart
Stack(
      children: <Widget>[
        Container(
          alignment: Alignment.center,
          child: _toggleAnimation.value == Alignment.centerRight
              ? _activeText
              : _inactiveText,
        ),
        Container(
          child: Align(
            alignment: _toggleAnimation.value,
            child: Container(
              width: widget.toggleSize,
              height: widget.toggleSize,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: _toggleColor ?? Colors.white,
                border: _toggleBorder,
              ),
              child: _icon,
            ),
          ),
        ),
      ],
    )
```

I also made the text appear centered, I think that is better to look at! Maybe adding a prop for that would be convenient but I only need it centered...

so far...
