### ISSUE TITLE
check state on app restart

### ISSUE THREAD

**Issue by prooshani** [boringdeveloper/FlutterSwitch#18]
Hi there,

I can't find any controller to change the switch's state outside the widget.
I want to check status of some parameters on app start and then toggle switches respectively without calling the onToggle() call routine, but I can't find any way to do so.

I would appreciate any suggestion/solution.

Thanks.

**Comment by boringdeveloper** [comment]
Hi @prooshani , passing a boolean variable with a value of `true` will change the switch's state.
