### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by SaintNicholas** [boringdeveloper/FlutterSwitch#30]
Dart 2.12 and Flutter 2 now support sound null safety (https://dart.dev/null-safety). We're using FlutterSwitch and looking to move everything to be null safe. Could you give me an idea of if/when you plan on supporting? Thanks!

**Comment by boringdeveloper** [comment]
Hi @SaintNicholas , I have published a pre-release with null-safety

**Comment by SaintNicholas** [comment]
Thanks!
