### ISSUE TITLE
Widget Disable Parameter

### ISSUE THREAD

**Issue by prooshani** [boringdeveloper/FlutterSwitch#33]
I am using this switch in one of the main sections of my app and sometimes, in some occasions, it would be very helpful to be able to disable the flutter_switch until some other parameters or inputs get ready or became available. 
It looks like there is no property available to disable/enable the flutter_switch widget at the moment and I think it would be great to be able to do so.

Thanks for your great job.

**Comment by muhib349** [comment]
Following.. I'm facing this problem too.

**Comment by boringdeveloper** [comment]
Hi @prooshani and @muhib349 , I opened a pull request for this. Maybe you can check it out and give some thoughts about it. I'll merge it tomorrow when no more additional recommendation is given. Thank you.
