### ISSUE TITLE
The switch comes on the center of the screen

### ISSUE THREAD

**Issue by shasank27** [boringdeveloper/FlutterSwitch#41]
The switch can't be positioned well.
Always comes to the center of the screen despite using start in CrossAxisAlignment

![Screenshot_1624361023](https://user-images.githubusercontent.com/53440570/122916353-69d57600-d37a-11eb-9a5e-4364e16668e5.png)

**Comment by boringdeveloper** [comment]
Hi @shasank27 , can I see a sample of your code? Thank you.

**Comment by boringdeveloper** [comment]
I was able to reproduce it, thank you for reporting. I Will issue a fix ASAP.

**Comment by shasank27** [comment]
Hey @boringdeveloper 
https://github.com/shasank27/Todoey-Hive/blob/master/lib/screens/task_screen.dart

**Comment by boringdeveloper** [comment]
@shasank27 I have tried the latest version of the package to your app. It seems to be working as intended now. If there are more bugs please do report it, thank you.

![image](https://user-images.githubusercontent.com/21273958/122980226-fdcf2e00-d3ca-11eb-9d38-541aac6d27bf.png)

_PS: Cool app btw!_

**Comment by shasank-periwal** [comment]
Thank you for fixing this so soon!
It still has bugs, gonna fix it in a day or two.
